### ISSUE TITLE
Can't add comment

### ISSUE THREAD

**Issue by Nico207** [cat-in-136/redmine_scheduling_poll#46]
Hi,

after clicking on [Add a comment], I can show the input box, but there is no "send" button.
Even if you click on [Vote], the text is not taken into account

![image](https://user-images.githubusercontent.com/1179972/70131815-3d1c1980-1683-11ea-8649-65682aced11b.png)

![image](https://user-images.githubusercontent.com/1179972/70131829-41483700-1683-11ea-8fb3-dc2f389ac7c1.png)

```
Environment:
Redmine version                4.0.5.stable.19319
Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
Rails version                  5.2.3
Database adapter               Mysql2

Scheduling Poll version        4.0.2
```

**Comment by cat-in-136** [comment]
Fill your comment to the "input box", and then push "Vote" button.
You'll see your comment on the issue page, not the poll page.

**Comment by Nico207** [comment]
You're right, I was looking in the wrong place.
Sorry about the false alarm.
