### ISSUE TITLE
permission users

### ISSUE THREAD

**Issue by ashrafalzyoud** [cat-in-136/redmine_scheduling_poll#54]
thx for your plugin @cat-in-136 

1-  Vote on scheduling polls
the user can see total votes and edit the poll items
iif u can edit it **TO BE** without see any  OTHER vote  and Voting Result and cant edit the poll items
2-  View scheduling polls
the user see all result for another users

i think the only admin can edit the poll items
and specific users can see the all result
-----------------------------------------------------
**if u can add new permission for normal users for vote only without any show any total vote or edit item??**

**Comment by cat-in-136** [comment]
No such a permission.

Only a use case to separate voting permission from poll item editing one is understandable. But this plugin is not intended to be an anonymous survey, so I would not implement the ability to fine-tune the way view-poll-result permission are displayed .
